# Copyright (C) 2023 Pedro Henrique Penna <pedrohenriquepenna@outlook.com>

[package]
name = "stack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
